### PR TITLE
Fixed PI implementation

### PR DESCRIPTION
**Pull request by n0toose**
Since the whole calculator does not depend on the standard C math (`math.h`) library, I decided to just take the library's definition of PI and adapt it.

### CODE REVIEW

**Comment by AlwaysLivid** [comment]
Bumping, could this change be considered/closed?

**Comment by n0toose** [comment]
CC: @humdingerb

**Comment by pulkomandy** [comment]
It uses sin(), cos(), etc which come from math.h. Why not just #include the file?

**Comment by AlwaysLivid** [comment]
> It uses sin(), cos(), etc which come from math.h. Why not just #include the file?

You're right, that probably slipped out of my radar back then. I'll open a pull request for that soon.

**Comment by n0toose** [comment]
> It uses sin(), cos(), etc which come from math.h. Why not just #include the file?

I remember having some very annoying problems with compilation because of an undeclared variable meant to represent π and I made this decision based on the presumption that this specific variable that's not in `math.h` *probably* used to work at some point, without knowing how exactly. So I think I tried to find a balance between preserving the code as much as possible while making it compilable. 

I'll try to look into it once again and I'll reconsider opening a new pull request, since `math.h` has been apparently included in `calculator.h` and my initial argument behind this change seems to have been incorrect.

**Comment by pulkomandy** [comment]
According to https://www.gnu.org/software/libc/manual/html_node/Mathematical-Constants.html it should be M_PI.

**Comment by n0toose** [comment]
@pulkomandy I think that this was the result of some weird thing between not having the appropriate header files installed and/or Paladin misbehaving.

**Pull request closed without merging**
